import sys; sys.path.insert(0,'/tmp/claude-0/-home-user/47b143d1-a9ed-5a02-adf0-c9c713677b02/scratchpad/debate/final')
from records import *
W='/tmp/claude-0/-home-user/47b143d1-a9ed-5a02-adf0-c9c713677b02/scratchpad/debate'
ch=parse_rewrite(W+'/rewrites/C1.md','NEW')
ch.pop('Unchanged',None); ch.pop('Noted',None)
# round-two corrections (scholar's facts, reader's wording)
R2={
'weston': {'note': "Weston (1850–1928) was a scholar of Arthurian romance. Following Frazer's <i>Golden Bough</i>, she argued that the Grail stories preserved the remains of an ancient fertility cult: a king whose wound lays his land waste, a cup and a lance that were sexual symbols before they were Christian relics, and a rite of initiation descended from the mystery cults of Attis and Mithra. Those cults, she says, were carried across the Roman Empire by Syrian merchants, slaves and soldiers (chapter XII). Medievalists have not accepted the argument. Eliot's headnote says the book suggested \"not only the title, but the plan and a good deal of the incidental symbolism of the poem,\" and recommends it \"to any who think such elucidation of the poem worth the trouble\"; in a lecture of 1956 he said he regretted \"having sent so many enquirers off on a wild goose chase after Tarot cards and the Holy Grail.\" The chapters the poem draws on most are II (The Task of the Hero), IX (The Fisher King) and XIII (The Perilous Chapel)."},
'frazer': {'note': "Frazer's twelve-volume study of magic and religion, which Eliot's headnote says \"has influenced our generation profoundly,\" argued that the myths of Adonis, Attis and Osiris, and by implication of Christ, tell one story, that of a god who dies with the harvest and returns with the spring, helped by rites in which a king is sacrificed or an effigy is buried or drowned. The two volumes Eliot names describe the \"gardens of Adonis,\" pots of quick-sprouting seed carried out with images of the dead god and \"flung with them into the sea,\" and the effigies of Osiris \"made of earth and corn\" that the priests buried so that grain would sprout from the god's body. Eliot's note on the Tarot says the Hanged Man \"is associated in my mind with the Hanged God of Frazer\"; the corpse planted in Stetson's garden (line 71) and Phlebas in the current (line 312) have been connected with the same rites. Frazer put a reproduction of Turner's painting <i>The Golden Bough</i> (1834) at the front of his first edition and opened his first page with it, describing it as a view of Lake Nemi; it in fact shows Lake Avernus and the Sibyl of Cumae, the prophetess of the poem's epigraph, holding the bough that admits Aeneas to the underworld."},
'petronius': {'note': "The speaker is Trimalchio, a freed slave grown enormously rich, boasting to his guests between courses; his dinner party is the longest continuous episode in what survives of the <i>Satyricon</i>. The Sibyl of Cumae, in Ovid's telling (<i>Metamorphoses</i> XIV), asked Apollo for as many years as the grains of sand in her hand and forgot to ask for youth to go with them; she foresees that she will shrink until only her voice is left. The typescript of the poem carried a different epigraph, from Conrad's <i>Heart of Darkness</i>, ending \"The horror! the horror!\"; Pound doubted that Conrad was weighty enough for the place, and Eliot put Petronius in its stead before publication."},
'dante-inf3': {'note': "Inside the gate (\"Abandon all hope\") but before the river Acheron, Dante finds the souls who were neither good nor bad, \"who lived without infamy and without praise,\" rejected by Heaven and refused by Hell, running for ever after a banner and stung by wasps. Eliot's note on line 63 quotes lines 55–57 as the source of the crowd flowing over London Bridge, and his note on line 46 says that the \"crowds of people\" in Madame Sosostris's cards \"appear later,\" which has generally been taken to mean this crowd. Eliot said in 1950 that Dante's poetry was still, \"after forty years,\" \"the most persistent and deepest influence\" on his own verse."},
'dante-inf4': {'note': "Limbo, the first circle of Hell, holds the virtuous who died unbaptised, Homer, Virgil and Aristotle among them; Dante calls them the \"great spirits\" (<i>spiriti magni</i>), and they are not tormented but live in desire without hope. Eliot's note on line 64 cites these lines. The comparison likens the sighs of the office crowd to those of Limbo, where there is grief but no torment, not to the cries of the damned."},
'dante-inf33': {'note': "Count Ugolino della Gherardesca of Pisa, imprisoned in 1288 with two sons and two grandsons and left to starve, gnaws in Hell on the skull of Archbishop Ruggieri, who betrayed him, and tells Dante the story. The verb in the passage, <i>chiavar</i>, has been read both as locking and as nailing up the door; the translation above has \"nailing up,\" and Eliot's \"key\" takes it as locking. His note on line 412 quotes these lines and then a passage from <i>Appearance and Reality</i> (1893) by F. H. Bradley, the philosopher on whom Eliot wrote his doctoral thesis; in it Bradley says that each person's experience \"falls within my own circle, a circle closed on the outside.\""},
'chaucer': {'note': "The Prologue opens with April rain ending the drought of March, sap rising, birds singing through the night and people longing to go on pilgrimage. Eliot's notes say nothing of Chaucer; readers have long set \"April is the cruellest month\" against these lines, in which the same month and the same rain are welcome. In Eliot's poem it is winter that \"kept us warm\" (lines 5–6)."},
'isaiah': {'note': "Eliot's notes do not cite Isaiah. The \"shadow of a great rock in a weary land\" of chapter 32 has long been recognised behind the \"shadow under this red rock\" of line 25; in Isaiah the shadow is promised together with \"rivers of water in a dry place,\" and the red rock of the poem gives shade but no water. In chapter 38 King Hezekiah, told to set his house in order because he will die, turns his face to the wall and weeps, and is granted fifteen more years. At line 426 the speaker, fishing on the shore, asks \"Shall I at least set my lands in order?\" and gets no answer; Eliot's note on the line before cites Weston's chapter on the Fisher King."},
'tristan': {'note': "Eliot's notes cite the libretto by act and verse: I, verses 5–8, and III, verse 24. The young sailor's song is the first thing sung in the opera; the sailor sings it unseen, from the masthead, above the deck where Isolde lies. The shepherd's \"Öd und leer das Meer!\" comes in Act III, answering Tristan's servant Kurwenal, who has asked whether any ship is in sight while Tristan lies wounded and waiting for Isolde. In the poem the hyacinth garden (lines 35–41) falls between the two quotations. Eliot heard <i>Tristan</i>, or its music in concert, in Boston in the autumn of 1909, at the start of his graduate year at Harvard, and wrote a poem about it, \"Opera,\" dated November 1909; Stravinsky, who met him in 1956, thought <i>Tristan</i> \"must have been one of the most passionate experiences of his life.\" Ludwig II of Bavaria, whose money paid for the first performance, was found dead in 1886 in the Starnberger See, the lake of line 8."},
'baudelaire-sept-vieillards': {'note': "The poet, walking through a dirty yellow fog on a Paris morning, meets a hideous old man, then another exactly like him, and another, seven in all, and flees home half mad. Eliot's note on line 60 quotes the first two lines. Stetson, hailed on King William Street at nine in the morning as a shipmate from the battle of Mylae (lines 69–70), has been read as Eliot's version of Baudelaire's daylight ghost."},
'webster-white-devil': {'note': "Webster's tragedy is about Vittoria Corombona, the \"white devil\" of the title, and her lover Brachiano, who has her husband and his own wife murdered. Vittoria's mother Cornelia sings the dirge over her son Marcello, killed by his brother Flamineo; Flamineo makes the speech about widows in the last scene, rising from a feigned death after Vittoria has fired at him what she took to be a loaded pistol. Eliot's notes cite the dirge at line 74 and Flamineo's speech at line 408. At line 74 the poem turns Webster's wolf, \"foe to men,\" into a Dog, \"friend to men.\" Eliot's \"Whispers of Immortality\" (1918) begins \"Webster was much possessed by death / And saw the skull beneath the skin.\""},
'shakespeare-tempest': {'note': "Ferdinand, washed ashore after the shipwreck, believes his father Alonso drowned; the song Ariel sings to him, unseen, describes a drowned man turned to coral and pearl. The song is not true. Alonso is alive, and the play ends with father and son reunited; in the poem the Phoenician Sailor of line 47 and Phlebas in Part IV stay drowned. Eliot's notes cite the scene at lines 192 and 257, and his note on the pearls of line 125 refers them back to lines 37 and 48; his note on Tiresias says the Phoenician Sailor \"is not wholly distinct from Ferdinand Prince of Naples.\" Ferdinand's \"the king my father's wreck\" becomes \"the king my brother's wreck\" and \"the king my father's death\" for the fisherman on the canal bank behind the gashouse (lines 191–192)."},
'shakespeare-antony': {'note': "Antony's officer Enobarbus describes Cleopatra's first appearance to Antony, in her barge on the river Cydnus; Eliot's note on line 77 cites the speech. The opening of Part II keeps the speech's manner, its blank verse and its inventory of gold, perfume and light, but moves the scene indoors, to a woman at her dressing table. The barge of Elizabeth and Leicester at line 279, for which Eliot's note cites the historian J. A. Froude, has been compared with this one."},
'shakespeare-hamlet': {'note': "Ophelia, mad after her father's death, leaves the stage with these words; she comes back once more in the same scene, with flowers, and her drowning is reported by Gertrude in scene vii. Eliot's notes say nothing of the line, which follows the pub's goodnights of lines 170–171 (\"Goonight Bill. Goonight Lou. Goonight May. Goonight. / Ta ta. Goonight. Goonight.\") without a break and ends Part II."},
'ovid-met6': {'note': "Tereus, king of Thrace, is bringing his wife Procne's sister Philomela to visit her when he rapes Philomela in a hut deep in the woods and cuts out her tongue; she weaves the crime into a cloth and sends it to her sister; Procne kills her son Itys and serves him to his father; Tereus, pursuing the sisters with a sword, and the sisters, fleeing, are all turned into birds. Ovid does not say which sister became the nightingale and which the swallow; the later tradition that Eliot follows makes Philomela the nightingale. Eliot's note on line 99 cites the story for the picture over the mantel in Part II; the \"Jug Jug\" of lines 103 and 204 is the nightingale's song as Elizabethan poets wrote it; and his note on line 429 refers the swallow back to \"Philomela in Parts II and III.\" Arthur Golding's translation of 1567, the one Shakespeare knew, gives the story in Book VI."},
'ovid-met3': {'note': "The passage is Book III, lines 324–331; Eliot's note on line 218 quotes the whole episode (lines 320–338) in Latin, calling it \"of great anthropological interest.\" Jupiter and Juno, disputing in jest which sex takes more pleasure in love, put the question to Tiresias, who has been both; he sides with Jupiter, Juno strikes him blind, and Jupiter gives him foresight in return. Eliot's note calls Tiresias \"the most important personage in the poem, uniting all the rest,\" and says that \"what Tiresias sees, in fact, is the substance of the poem.\""},
'middleton-wbw': {'note': "Livia, a rich widow acting as the Duke of Florence's procuress, keeps Bianca's mother-in-law at chess while the Duke rapes Bianca in the gallery above; her remarks on the game double as commentary on what is happening upstairs. Eliot's note on line 137 cites \"the game of chess in Middleton's <i>Women beware Women</i>\"; the title of Part II has also been connected with Middleton's <i>A Game at Chess</i> (1624), an anti-Spanish satire that ran for nine days at the Globe before the Privy Council stopped it. Eliot's essay on Middleton (1927) calls him \"a great observer of human nature, without fear, without sentiment, without prejudice.\""},
}
for rid,d in R2.items(): ch.setdefault(rid,{}).update(d)
print(sorted(ch)); print({k:sorted(v) for k,v in ch.items()})
apply('/mnt/project-files/commentary/site/sources.txt', ch)
import json; open(W+'/final/C1.json','w').write(json.dumps(ch,ensure_ascii=False,indent=1))
