# Batch C2, final: the library's second half (sources.txt). rewrites/C2.md + r2/C2-scholar.md (facts) + r2/C2-reader.md (wording).
import sys, json, re
sys.path.insert(0, '/tmp/claude-0/-home-user/47b143d1-a9ed-5a02-adf0-c9c713677b02/scratchpad/debate/final')
import records
from apply_B import smart
SITE = '/mnt/project-files/commentary/site/'
ch = records.parse_rewrite('/tmp/claude-0/-home-user/47b143d1-a9ed-5a02-adf0-c9c713677b02/scratchpad/debate/rewrites/C2.md', 'plain')

def setf(rid, field, text): ch.setdefault(rid, {})[field] = text
def sub(rid, field, old, new):
    t = ch[rid][field]; assert old in t, (rid, field, old); ch[rid][field] = t.replace(old, new)

setf('day-parliament-of-bees', 'note', '''Twelve “characters,” sketches of good and bad men, who appear as bees. The lines Eliot’s note quotes are spoken by Polypragmus, “a mere vainglorious reveller,” describing the shows he means to stage in his hall. A noise of horns and hunting is to bring Actaeon to Diana “in the spring,” where all shall see her naked, and Actaeon’s hounds are then to tear their master. The story is from Ovid’s <i>Metamorphoses</i>, where the hunter Actaeon comes upon the goddess Diana bathing, is turned into a stag and is killed by his own dogs. Eliot keeps the shape of Day’s sentence and puts “horns and motors” for the hunt, and Sweeney and Mrs Porter for Actaeon and Diana.''')
setf('verlaine-parsifal', 'trans', '''Parsifal has overcome the Maidens, their pretty chatter and amusing lust, and his own leaning toward the Flesh, the leaning of a virgin boy whom all that tempts to love light breasts and that pretty chatter; he has overcome the beautiful Woman with the subtle heart, spreading her cool arms and her exciting bosom; he has overcome Hell and returns to his tent with a heavy trophy on his boyish arm, with the lance that pierced the supreme Side! He has healed the king, and here he is king himself, and priest of the most holy essential Treasure. In a robe of gold he adores, glory and symbol, the pure vessel where the real Blood shines. And, oh, those children’s voices singing in the dome!''')
setf('verlaine-parsifal', 'note', '''Verlaine’s sonnet on Wagner’s last opera, written for the <i>Revue wagnérienne</i>, a Paris journal devoted to Wagner, and printed there in January 1886, gives the plot in thirteen lines: the flower-maidens, the temptress Kundry, the recovered spear, the healed king. The fourteenth line is the boys’ choir in the dome of the Grail temple. Eliot’s note cites the sonnet. In the poem the line comes straight after the ballad about Mrs Porter, which Eliot’s note says was “reported to me from Sydney, Australia.” In Wagner, as in the romances Jessie Weston discusses in <i>From Ritual to Romance</i>, the book Eliot’s headnote cites, the knight heals the wounded king; the poem’s Fisher King is still fishing at line 425, “with the arid plain behind me.”''')
setf('lyly-campaspe', 'note', '''The Elizabethan convention that the nightingale sings “jug jug” and cries “tereu,” calling on Tereus, the king who raped Philomela, is at its plainest in this song from Lyly’s court comedy. The songs in Lyly’s plays were first printed in the collected edition of 1632, and whether he wrote them is disputed. Eliot does not cite Lyly. “Jug Jug” at line 103 and the birdsong at lines 203–206 use the convention, and at line 205, between the bird’s “Jug jug” and its “Tereu,” stands “So rudely forc’d.”''')
setf('sappho-104', 'note', '''Two lines that survive because Demetrius, an ancient Greek critic, quoted them in his treatise <i>On Style</i> (section 141), for the charm of their repeated “you bring.” Eliot’s note says his lines “may not appear as exact as Sappho’s,” and that he had in mind the “longshore” or “dory” fisherman “who returns at nightfall.” Byron imitated the lines in <i>Don Juan</i> (Canto III, stanza 107), and Stevenson’s “Requiem” has “Home is the sailor, home from sea”; both have been cited as English links between Sappho and Eliot’s lines 220–221.''')
setf('augustine-confessions', 'note', '''Augustine’s account, in Book III, of his student years at Carthage, “a cauldron of unholy loves,” and, in Book X, of the pull that beautiful things still have on a man trying to keep his eyes on God. In the Latin, <i>sartago</i>, a cauldron or frying pan, plays on <i>Carthago</i>. Eliot’s words are Pusey’s translation of 1838, with the first sentence rearranged in his note as “to Carthage then I came, where a cauldron of unholy loves sang all about mine ears.” His second Augustine note says that setting “these two representatives of eastern and western asceticism,” Augustine and the Buddha, side by side at the end of Part III “is not an accident.”''')
setf('buddha-fire-sermon', 'note', '''In the account Warren translates from the Mahāvagga, a book of the Pali scriptures, the Buddha preached the sermon to a thousand former fire-worshipping ascetics on Gayā Head, a hill near the town of Gaya in Bihar, India, soon after his enlightenment. Eliot studied Sanskrit and Indian philosophy at Harvard in 1911–13 and knew Warren’s <i>Buddhism in Translations</i> (1896). His note says the sermon “corresponds in importance to the Sermon on the Mount,” sends the reader to Warren for the complete text, and calls Warren “one of the great pioneers of Buddhist studies in the Occident.” Part III takes its title from the sermon, and line 308 its word, “Burning.”''')
setf('brihadaranyaka', 'note', '''Eliot read the Upanishads in Sanskrit at Harvard under Charles Lanman in 1911–13. His note gives the reference as Brihadaranyaka 5, 1 (the passage is 5.2 in the standard numbering) and sends the reader to Paul Deussen’s German translation of 1897. In the fable each group hears in the one syllable the command it needs. Eliot puts the three commands in a different order, glosses them in his note as “Give, sympathize, control,” and follows each with a passage in which the speaker answers it. “Shantih,” his last note says, is “a formal ending to an Upanishad,” and “The Peace which passeth understanding” is “a feeble translation of the content of this word”; later editions soften this to “our equivalent to this word.”''')
setf('shackleton-south', 'note', '''In May 1916, after the <i>Endurance</i> had been crushed in the ice and the party had come through the open-boat voyage across the Southern Ocean, Shackleton and two of his men, Worsley and Crean, crossed the mountains of South Georgia on foot to reach the whaling station at Stromness. Eliot’s note says he had forgotten which expedition it was, “but I think one of Shackleton’s,” and remembers the party’s “constant delusion that there was one more member than could actually be counted”; Shackleton’s own words are that “it seemed to me often that we were four, not three.” Eliot’s headnote to Part V names the journey to Emmaus as one of the section’s three themes. In that story two disciples walking from Jerusalem after the crucifixion are joined by a third whom they do not recognise as the risen Christ; the lines beginning at 360 ask who the third is.''')
setf('nerval-desdichado', 'note', '''The opening sonnet of Nerval’s <i>Chimères</i>, first printed in December 1853, in the last years of his illness; he hanged himself in a Paris street on 26 January 1855. The title, a Spanish word, is usually traced to the shield of the Disinherited Knight in Walter Scott’s <i>Ivanhoe</i>; in Spanish it means “unfortunate” rather than “disinherited.” The “tour abolie” is often read as the Tower card of the Tarot. In the last lines the poet says he has twice crossed Acheron, the river of the dead, and come back, and still plays Orpheus’s lyre. Eliot’s note cites the sonnet; he quotes its second line only.''')
setf('london-bridge', 'note', '''The rhyme runs through building materials that fail until a watchman is set. Folklorists of James Frazer’s generation, Alice Gomme among them, connected it with the belief that a bridge was once made to stand by burying a victim in its foundations; Iona and Peter Opie, in <i>The Oxford Dictionary of Nursery Rhymes</i>, treat the connection with caution. Eliot’s crowd crossed the real London Bridge at line 62. Here the rhyme opens the run of quotations at lines 427–430, the “fragments” of line 431; the others are in Italian, Latin and French, with three English words, “O swallow swallow,” set in the Latin line.''')
setf('shakespearian-rag', 'note', '''Published in 1912 and advertised as a number from that year’s Ziegfeld Follies, the Broadway revue. In 2017 the music critic Matthew Guerrieri searched the files of <i>Variety</i>, the show-business trade paper, and found no sign that it was sung in the show; the first performance he could find was in vaudeville, at the Columbia Theatre, New York, on 5 January 1913. The lyric has Shakespeare’s characters dancing the ragtime steps of the day. Eliot’s “Shakespeherian,” with its extra syllable, is generally read as deliberate, giving the word the rag’s syncopation; the poem also reverses the song’s “intelligent … elegant.” No recording from the period is known.''')
setf('death-of-st-narcissus', 'note', '''Set in type for <i>Poetry</i> (Chicago) in 1915 and withdrawn in proof; first published in 1950. The poem is about a saint who is sure he had been a tree, a fish and a young girl, and who dies pierced with arrows. The manuscript survived among the papers Eliot sent in 1922 to John Quinn, the New York lawyer and collector, with the <i>Waste Land</i> drafts, and is now in the Berg Collection of the New York Public Library. After these two lines the speaker promises to show the listener something other than the listener’s own shadow, sprawling on the sand at daybreak or leaping behind the fire. <i>The Waste Land</i> keeps the second line, with “gray” changed to “red,” and reshapes the first. The poem is still in copyright, so only its first two lines are given here.''')
setf('conrad-hod', 'what', '''The epigraph on the typescript, replaced before publication by the passage from Petronius.''')
setf('conrad-hod', 'note', '''The last words of Kurtz, the trader whom the narrator, Marlow, has gone up the river to find, stood at the head of the typescript of Part I as the poem’s epigraph. Pound wrote that he doubted whether Conrad was “weighty enough to stand the citation.” Eliot answered that it was “much the most appropriate I can find, and somewhat elucidative,” and Pound withdrew the objection; Eliot nevertheless replaced it with the passage from Petronius that stands there now. “The heart of light” at line 41 has been read as an inversion of Conrad’s title. The story is told on a yawl at anchor in the Thames estuary at dusk, with London upriver.''')
setf('huxley-crome-yellow', 'note', '''Huxley’s country-house satire was published in November 1921. Its Mr. Scogan, a cynical guest who dresses up as an old gypsy woman to tell fortunes at the village fête under the name “Sesostris, the Sorceress of Ecbatana,” is the accepted source of Madame Sosostris. Asked about it by the critic Grover Smith, Eliot wrote to him on 10 March 1952 that he was “almost certain” he had taken the name from <i>Crome Yellow</i> without being conscious of doing so. Huxley and Eliot had known each other since the war years through Lady Ottoline Morrell’s circle at Garsington, her house near Oxford.''')
setf('eliot-frontiers', 'note', '''A lecture given at the University of Minnesota on 30 April 1956, to an audience of about fourteen thousand, and printed in <i>On Poetry and Poets</i> (1957). Thirty-four years on, Eliot said he had meant only to list his references, “spiking the guns” of critics who had accused his earlier poems of plagiarism. The poem’s first printings, in two magazines, the <i>Criterion</i> and the <i>Dial</i>, had no notes; when Boni & Liveright were to make it a book, it was found too short, and he expanded the notes to fill the pages, with the result he called “bogus scholarship.” He regretted sending readers on “a wild goose chase after Tarot cards and the Holy Grail,” and said the notes could not now be removed, since anyone who bought his poems and found them missing would ask for his money back.''')
setf('spenser-prothalamion', 'note', '''A “spousal verse,” as its title page calls it, for the double wedding of the Earl of Worcester’s daughters, Elizabeth and Katherine Somerset. The poet, out of favour at court, walks by the Thames and sees nymphs gathering flowers for two swans, who stand for the brides. Eliot’s note to line 176 cites the poem. He keeps Spenser’s refrain; his nymphs are twice said to have departed (lines 175 and 179), and where Spenser’s river carries the swans, his bears no litter of summer nights. Spenser’s poet is himself unhappy, walking by the river to ease the “sullein care” of a fruitless wait at court.''')
sub('pervigilium-veneris', 'note', 'between the second and fifth centuries AD, most likely the fourth,', 'between the second and fifth centuries AD,')
setf('pervigilium-veneris', 'date', '2nd–5th century AD')
sub('marvell-coy-mistress', 'note', 'not to wait: time is short,', 'not to wait, because time is short,')
sub('marvell-coy-mistress', 'note', 'in the Times Literary Supplement of 31 March 1921', 'in the <i>Times Literary Supplement</i> of 31 March 1921')
sub('bradley', 'note', '“Dayadhvam,” sympathise.', '“Dayadhvam,” sympathize.')

if __name__ == '__main__':
    for rid, f in ch.items():
        for k, v in f.items(): assert '\n' not in v, (rid, k)
    records.apply(SITE + 'sources.txt', ch)
    # quotes: regularise the English fields of every record (what, note, trans), not passage
    text = open(SITE + 'sources.txt', encoding='utf-8').read()
    recs = records.parse(text); assert records.serialize(recs) == text
    n = 0
    for fields in recs:
        for fl in fields:
            if fl[0] in ('what', 'note', 'trans', 'title'):
                s = smart(fl[1])
                if s != fl[1]: fl[1] = s; n += 1
    open(SITE + 'sources.txt', 'w', encoding='utf-8').write(records.serialize(recs))
    print('quotes regularised in', n, 'fields')
    json.dump(ch, open('/tmp/claude-0/-home-user/47b143d1-a9ed-5a02-adf0-c9c713677b02/scratchpad/debate/final/C2.json', 'w'), ensure_ascii=False, indent=1)
