# Batch D, final: the listening room (listen.txt). rewrites/D.md + r2/D-scholar.md (facts) + r2/D-reader.md (wording).
import sys, json
sys.path.insert(0, '/tmp/claude-0/-home-user/47b143d1-a9ed-5a02-adf0-c9c713677b02/scratchpad/debate/final')
import records
SITE = '/mnt/project-files/commentary/site/'
ch = records.parse_rewrite('/tmp/claude-0/-home-user/47b143d1-a9ed-5a02-adf0-c9c713677b02/scratchpad/debate/rewrites/D.md', 'plain')
def setf(rid, field, text): ch.setdefault(rid, {})[field] = text
def sub(rid, field, old, new):
    t = ch[rid][field]; assert old in t, (rid, field, old); ch[rid][field] = t.replace(old, new)

# Reader, round 2 (wording); the scholar's round-two corrections of fact are folded in below under SCHOLAR.
setf('eliot-1935-pennsound-columbia', 'body', '''The same Columbia series in two complete versions, divided by section, on PennSound’s own page. PennSound holds it with the permission of the Eliot estate, for study and teaching. It gives the date as 1935, though its own headnote says the Columbia recordings were made in 1933, 1935 and later; for the date of 1933 the Poetry Archive refers readers to Richard Swigg’s <i>Quick, Said the Bird</i> and Jason Camlot’s <i>Phonopoetics</i>.''')
setf('eliot-later-harperaudio-archive', 'body', '''The later recording, the one issued on record. Caedmon issued it first; HarperCollins, which later bought Caedmon, reissued it under its Harper Audio name. This copy was put out by Harper Audio on 18 January 1994 through the Internet Multicasting Service, an early internet radio channel, as sound files at 8 kHz; HarperCollins consented to that distribution only. The Internet Archive keeps it as a thirty-one-minute MP3. The sound is poor, about the quality of a telephone line. The Poetry Archive dates the recording 1946; the item itself gives no year.''')
setf('irons-atkins-bbc-radio4-2012', 'title', '''Jeremy Irons reads the poem, BBC Radio 4, 2017''')
setf('irons-atkins-bbc-radio4-2012', 'who', '''Jeremy Irons, presented by Martha Kearney with Jeanette Winterson, Rowan Williams and Jackie Kay''')
setf('irons-atkins-bbc-radio4-2012', 'when', '''Broadcast 1 January 2017''')
setf('irons-atkins-bbc-radio4-2012', 'body', '''Irons reads the poem on his own in this Radio 4 programme, broadcast on 1 January 2017 and kept by the Internet Archive in a recording made off the air. It was the third of five programmes in which Martha Kearney and her guests introduced his readings of Eliot; the guests here are Jeanette Winterson, Rowan Williams and Jackie Kay. Five years earlier, on 30 March 2012, Irons and Eileen Atkins had shared the poem’s voices between them in another Radio 4 broadcast, introduced by Rowan Williams, Jackie Kay, Matthew Hollis and Sean O’Brien. The BBC’s page for that reading, linked here, has the details and no audio; the copies of it on YouTube are listeners’ uploads and are not played here.''')
setf('irons-cusack-borris-festival', 'body', '''In June 2022, the poem’s centenary year, Irons and Cusack read it at the festival, introduced by James Lever. The festival’s own recording, posted in 2023, runs fifty-two minutes, with the introduction and the audience left in.''')
setf('shaw-bbc-newsnight-clip', 'body', '''Deborah Warner directed Fiona Shaw in the poem as a piece of theatre, with Shaw alone on a bare stage taking every voice. It opened in Brussels in May 1995 and toured, and {link:shaw-warner-film-cannes-1996|Warner’s film of it, made for the BBC, was shown at Cannes} in May 1996. In 1997 the staging ran at Wilton’s Music Hall in the East End, which is why that hall is on the site’s map. The clip here is the BBC’s own, of Shaw performing part of the poem on Newsnight in January 2015, fifty years after Eliot’s death. The film itself circulates only in unofficial copies, which are not played here.''')
setf('gotterdammerung-solti-1964-rhinemaidens', 'body', '''The Thames-daughters’ refrain at lines 277 to 278 and 290 to 291 quotes the Rhinemaidens’ cry from the last act of Wagner’s Götterdämmerung, where they rise from the river to beg Siegfried for the ring. The scene begins on side nine, “Act III Scene 1”.''')
setf('bl-1922-first-edition-archive-duke', 'body', '''The book this site follows, scanned page by page by Duke University Libraries. The marginal line numbers are printed every ten lines. On page 42 the line “If there were water” is set as if it were the end of the line before it, carried over for want of room, and the numbering skips it. From there the 1922 numbers run one behind the count used here.''')
setf('bl-1922-first-edition-archive-byu', 'body', '''The library’s record calls this copy no. 596 of the thousand and cites Gallup A6a, the 1922 edition’s entry in Donald Gallup’s bibliography of Eliot, while also noting a fourth printing. It is not a second scan of the first printing. The title page reads Horace Liveright, the verso “Fourth Printing, April, 1930”, and it has no limitation statement, the note that numbered each copy of the first printing. The pages are the 1922 setting of type, page for page and with the same marginal numbers; “hot water” at line 135 and “Heimat” at line 32, where letters are missing in the Duke copy, print cleanly here. Copies of the first printing exist in two states: in the earlier, line 339 reads “Dead mountain mouth of carious teeth”; in the later the a of “mountain” had dropped out and it reads “mount in”. Duke’s copy is the later state, and this printing still reads “mount in”.''')
setf('dial-november-1922-archive', 'body', '''The poem as it first reached American readers, without the notes, in the magazine that gave Eliot its two-thousand-dollar award that year. Here the first line’s “cruellest” is spelled “cruelest”, with one l. The poem’s earliest printing of all was in The Criterion, the London magazine Eliot edited, in October 1922; that issue is on HathiTrust, where it can be read in full from the United States.''')
setf('nypl-digital-waste-land-typescript', 'body', '''The typescript and manuscript pages, with Pound’s cuts and comments and notes by Eliot’s wife Vivien, which Eliot sent in October 1922 to John Quinn, the New York lawyer and collector. After Quinn’s death they passed to his sister and then to his niece, who sold them to the New York Public Library’s Berg Collection in 1958; the library announced the purchase in 1968, after Eliot’s death. The library has digitised the pages but shows the images only in the building, so the link here goes to its record, not to the pages. The way to read them is the facsimile edition that Eliot’s widow, Valerie Eliot, published in 1971, reissued by Faber in 2022 with the pages in colour.''')
setf('frazer-adonis-attis-osiris-1906', 'body', '''Eliot’s headnote names “the two volumes Adonis, Attis, Osiris”, which are Part IV of the third edition of The Golden Bough (1914). This is the book’s first edition of 1906, in one volume, where Frazer’s account of the dying and reviving gods, the gardens of Adonis and the images of the god thrown into the sea first appeared. The other book the headnote names, Jessie Weston’s From Ritual to Romance, is {link:gutenberg-4090-weston|on Project Gutenberg}, and so is {link:gutenberg-3623-frazer-golden-bough|the one-volume Golden Bough} of 1922.''')

# Part II's proposal: the three accounts of the rag (gloss, library, listening room) tell one story
setf('shakespearian-rag-york-sheet-music', 'body', '''Line 128’s “O O O O that Shakespeherian Rag” adds a syllable to a song of 1912 advertised as a number from that year’s Ziegfeld Follies, though no performance in the show has been traced and the first known was in vaudeville in January 1913; the cover spells it “Shakesperian”. York University in Toronto has the sheet music, scanned with its cover. No recording from the time has turned up in the Library of Congress or the Internet Archive.''')
SCHOLAR = {  # r2/D-scholar.md, in the reader's wording
'eliot-1935-pennsound-columbia': {'body': '''The same Columbia series in two complete versions of different lengths, about twenty-five and twenty-eight minutes, each divided by section, on PennSound’s own page. PennSound holds it with the permission of the Eliot estate, for study and teaching. It gives the date as 1935, though its own headnote says the Columbia recordings were made in 1933, 1935 and later; for the date of 1933 the Poetry Archive refers readers to Richard Swigg’s <i>Quick, Said the Bird</i> and Jason Camlot’s <i>Phonopoetics</i>.'''},
'eliot-later-harperaudio-archive': {'body': '''The later recording, the one issued on record. Caedmon issued it first; Harper & Row, which bought Caedmon in 1987 and became HarperCollins, reissued it under its Harper Audio name. This copy was put out by Harper Audio on 18 January 1994 through the Internet Multicasting Service, which had started the first internet radio station the year before, on its Internet Town Hall channel, as sound files at 8 kHz; HarperCollins consented to that distribution only. The Internet Archive keeps it as a thirty-one-minute MP3. The sound is poor, about the quality of a telephone line. The Poetry Archive dates the recording 1946; the item itself gives no year.'''},
'guinness-argo-full-bookyards': {'body': '''Guinness’s readings of The Waste Land and Four Quartets were issued by Argo in its series British Poets of Our Time, made with the Arts Council of Great Britain and the BBC; the double album of 1975 gathers them with eight shorter pieces, Prufrock and Journey of the Magi among them. The copy online is a listener’s upload to YouTube, so it is linked from here and not played on this page.'''},
'shakespearian-rag-york-sheet-music': {'body': '''Line 128’s “O O O O that Shakespeherian Rag” adds a syllable to a popular song of 1912, usually said to have been sung in that year’s Ziegfeld Follies, though no performance in the show has been traced; the cover spells it “Shakesperian”. York University in Toronto has the sheet music, scanned with its cover. No recording from the time has turned up in the Library of Congress or the Internet Archive.'''},
'xc715748-hermit-thrush-by-sa': {'body': '''A second recording. Eliot’s note on line 357 speaks of the hermit-thrush’s “water-dripping song”; the bird sings at lines 356 to 358. Licensed CC BY-SA, so this one may be reused with credit and under the same licence.'''},
'frazer-adonis-attis-osiris-1906': {'body': '''Eliot’s headnote names “the two volumes Adonis, Attis, Osiris”, which are Part IV of the third edition of The Golden Bough (1914). This is the book’s first edition of 1906, in one volume. It gives Frazer’s account of the dying and reviving gods, the gardens of Adonis and the images of the god thrown into the sea, first set out in The Golden Bough of 1890 and enlarged here. The other book the headnote names, Jessie Weston’s From Ritual to Romance, is {link:gutenberg-4090-weston|on Project Gutenberg}, and so is {link:gutenberg-3623-frazer-golden-bough|the one-volume Golden Bough} of 1922.'''},
}
def apply_scholar():
    for rid, f in SCHOLAR.items():
        for k, v in f.items(): setf(rid, k, v)

if __name__ == '__main__':
    apply_scholar()
    for rid, f in ch.items():
        for k, v in f.items(): assert '\n' not in v, (rid, k)
    # placeholders must survive
    before = open(SITE + 'listen.txt', encoding='utf-8').read()
    import re
    ph_before = sorted(re.findall(r'\{link:[^}]*\}|\{parts\}', before))
    records.apply(SITE + 'listen.txt', ch)
    after = open(SITE + 'listen.txt', encoding='utf-8').read()
    ph_after = sorted(re.findall(r'\{link:[^}]*\}|\{parts\}', after))
    ids_b = sorted(set(re.findall(r'\{link:([^|}]*)', before))); ids_a = sorted(set(re.findall(r'\{link:([^|}]*)', after)))
    print('link ids before/after equal:', ids_b == ids_a, '| {parts} count', before.count('{parts}'), after.count('{parts}'))
    json.dump(ch, open('/tmp/claude-0/-home-user/47b143d1-a9ed-5a02-adf0-c9c713677b02/scratchpad/debate/final/D.json', 'w'), ensure_ascii=False, indent=1)
